### ISSUE TITLE
Add components steps to screen resize test.

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/behat-relativity#2]
Currently, there are no components relative position assertions in https://github.com/integratedexperts/behat-relativity/blob/master/tests/behat/features/screen_resize.feature file.

We need to add assertions for elements that change dimension depending on the screen size to make sure that "responsiveness" is properly picked up.

**Comment by bladeaweb** [comment]
https://github.com/integratedexperts/behat-relativity/pull/3
